### ISSUE TITLE
Sensor device won't wake from deep sleep

### ISSUE THREAD

**Issue by jtannenba** [HarringayMakerSpace/ESP-Now#17]
I tried this with a pair of nodemcu 12E's and the one with the sensor goes to sleep and never wakes up.  When it first sends data, it goes ok, returns a status = 0, then goes to sleep and never wakes back up.  I don't see anything wrong with the code.  I guess I don't understand how it is supposed to wake up.

bme280 init=60
temp=75.830002, humidity=18.812500, pressure=26.775942
This mac: CC:50:E3:DE:18:3A, target mac: 5c50e3de1428, channel: 4
send_cb, send done, status = 0
Up for 165 ms, going to sleep for 954 secs...

Any insight would be appreciated.

**Comment by torntrousers** [comment]
On the NodeMCU that goes to sleep and never wakes up - do you have a jumper connecting the GPIO16 pin to to the RST pin?

**Comment by jtannenba** [comment]
No, did I miss that?

**Comment by jtannenba** [comment]
That was it.  Didn't see instructions to tie GPIO16 pin to to the RST pin.  I'm still new to this stuff. 
Thanks
